### ISSUE TITLE
Warlord and Relics not available to select for valid units

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-9e#12244]
Warlord and Relics not available to select for valid units.  
Replicated with Space Marines: Salamanders: Adrax Agitone and Orks: Warboss in Mega Armor

There was a similar issue file against orks earlier with the same error displaying.  
Oddly in the Ork case when I added Gazgull Thrakka (supreme unit automaticly set as warlord) the issue was resolved.  Could there be a missed flag pass not enabling the selection?

1. Create a new list (replicated with slamanders and Orks
2. Select Arks of Omens detachment
3. select HQ unit Adrax Agitone(sallies) Warboss in Mega Armor (orks)
4. Note warlord traits and relics are unavailable. 

Expected
Units capable of recieving relics and warloard traits can select them.  

![Screenshot_20230115-164756](https://user-images.githubusercontent.com/52298216/212574177-3e9bfde8-f130-4809-a8ef-c5af441ed1f5.jpg)

 - OS: Android
 - BattleScribe version v2.03.25.338
 - Release version v 9.7.0

**Additional context**

**Comment by acebaur** [comment]
Adrax is functioning properly. Make sure you have the correct detachment and game type selected. Also named characters can't have relics

**Comment by BlueWinds** [comment]
~~I am seeing something similar for the Canoness in Adepta Sororitas, unable to select a warlord trait. See attached list - if I deselect the Warlord trait stratagem which triggers the a validation error, there's no option to give her a warlord trait at all.~~

Fixed in 9.7.1

.rosz file, renamed to .zip so it can be attached here.

[Sisters of the New Dawn.zip](https://github.com/BSData/wh40k/files/10423488/Sisters.of.the.New.Dawn.zip)

**Comment by ghost** [comment]
@acebaur I'm still unable to see the option to give Adrax his warlord trait when he is not the warlord.  
This can be replicated by setting up a basic detachment, adding any charter as a Warlord, and Adrax has neither the standard nor salamander based warlord trait option to pay CP for.  ( i.e. hero if the chapter)

All detachment setting are as expected and the new compulsory setting is configured

This is why I was wondering if the Warlord was not getting set correctly, enabling the option for the secondary warlord trait

**Comment by BlueWinds** [comment]
My issue is fixed in 9.7.1, thank you!
